### ISSUE TITLE
GridX Documentation Gallery

### ISSUE THREAD

**Issue by LetaRogers** [evanhw/gridx#1]
I have two suggestions for your GridX Documentation Gallery...

(1) Re: http://oria.github.io/gridx/gallery.html#export_print

The description states, "This module provides the API to print grid contents or provide print preview." However, the demo shows only the export to CSV example (http://oria.github.io/gridx/gridx/demos/test_grid_exporter.html). I suggest you have separate entries for "export" and "print". Print should link to the example page from the download folder at /gridx/tests/test_grid_printer.html. This html page does not appear to exist in http://oria.github.io/gridx/gridx/demos/ 

(2) Re: http://oria.github.io/gridx/about.html

The link for "Please provide suggestions or report issues on GridX GitHub Issues" shows the correct link in the text, but the link itself just loads http://oria.github.io/gridx/about.html

I have a lot of other ideas on improving the documentation. If you prefer I can email them to you rather than post this as an issue.

**Comment by evanhw** [comment]
gridx has been moved to https://github.com/oria/gridx since long time ago, so closing
