### ISSUE TITLE
GridX fails to load under Cordova's WebView on mobile devices: files have underscores in names and there are html templates, which fail to load

### ISSUE THREAD

**Issue by ghost** [evanhw/gridx#2]
There are 2 problems when trying to use GridX with Cordova environment.
In such environment, all files are kept in local filesystem. 
This implies the following restrictions (with Chromium):
1. file or directory name cannot contain underscore "_" in the beginning - and in GridX, there are several files, that DO contain underscores
2. the only allowed files that can be loaded via DOJO's XHR system are JS files.
GridX contains HTML templates, which are requested using DOJO's !text loader.
This request fails, disabling the application.

Workaround:
1. rename all files with leading underscores - quite easy
2. instead of HTML files as templates, create JS files, which contain functions returning HTML template as string:

function __template_getGrid() {
  var ret = "<div>........."; // multiline template
  return ret;
};

 then, change the require invocation as to normal JS script request:

require(["...","gridx/templates/grid"],function(...., template, ...) {

and add a line inside a require callback, usually like:

template = __template_getGrid();

I have managed to make it work.

**Comment by evanhw** [comment]
gridx has been moved to https://github.com/oria/gridx since long time ago, so closing
