### ISSUE TITLE
GridX Virtual Scroll is very slow on Samsung mobile devices

### ISSUE THREAD

**Issue by ghost** [evanhw/gridx#3]
The virtual scroll should enable to perform a fast-scrolling through multiline grid,
but instead, on Samsung Galaxy Tab and Tab 2, it does only move for a few lines at a time. 
This behaviour makes it unacceptable for our Customers.

**Comment by evanhw** [comment]
gridx has been moved to https://github.com/oria/gridx since long time ago, so closing
