### ISSUE TITLE
In Mac firefox, the scrollers can not show

### ISSUE THREAD

**Issue by funroller** [evanhw/gridx#4]
firefox version 33.1
The bellow snapshot is the horizontal demo, no horizontal scroller bar shows.
![firefox_mac_screeshot](https://cloud.githubusercontent.com/assets/8960167/5041647/eaedca68-6c01-11e4-99aa-78fb8a804d27.png)
Same for the vertical scroller

**Comment by funroller** [comment]
Any one can take a look?

**Comment by evanhw** [comment]
Hi funroller,

gridx has been moved to https://github.com/oria/gridx for a long time. Please raise gridx related issues to https://github.com/oria/gridx/issues/

I also ported this issue there as https://github.com/oria/gridx/issues/307

Thanks!

**Comment by evanhw** [comment]
Migrated issue to https://github.com/oria/gridx/issues/307 so closing,

**Comment by funroller** [comment]
Hi Evanhw, will track by 307, thanks
